### ISSUE TITLE
build _/home/anantharal/go/pkg/mod/github.com/hegedustibor/htgo-tts@v0.0.0-20200606215327-a8f5a5c8e477/handlers: cannot find module for path _/home/anantharal/go/pkg/mod/github.com/hegedustibor/htgo-tts@v0.0.0-20200606215327-a8f5a5c8e477/handlers

### ISSUE THREAD

**Issue by anantxx** [hegedustibor/htgo-tts#4]
For go get "github.com/hegedustibor/htgo-tts" command, facing the following issue
 
go: finding github.com/hegedustibor/htgo-tts latest
build _/home/go/pkg/mod/github.com/hegedustibor/htgo-tts@v0.0.0-20200606215327-a8f5a5c8e477/handlers: cannot find module for path _/home/go/pkg/mod/github.com/hegedustibor/htgo-tts@v0.0.0-20200606215327-a8f5a5c8e477/handlers

**Comment by hegedustibor** [comment]
I pushed a fix commit. Please, try again. Thanks for sent this issue.
